server.port=${PORT:8080}

# Auth (user-json-service дотор байдаг)
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=${JSON_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**
spring.cloud.gateway.routes[0].filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

# User JSON Service
spring.cloud.gateway.routes[1].id=json-service
spring.cloud.gateway.routes[1].uri=${JSON_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.routes[1].predicates[0]=Path=/users/**
spring.cloud.gateway.routes[1].filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

# File Manager Service
spring.cloud.gateway.routes[2].id=file-service
spring.cloud.gateway.routes[2].uri=${FILE_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.routes[2].predicates[0]=Path=/files/**
spring.cloud.gateway.routes[2].filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

# Mail Service
spring.cloud.gateway.routes[3].id=mail-service
spring.cloud.gateway.routes[3].uri=${MAIL_SERVICE_URL:http://localhost:8083}
spring.cloud.gateway.routes[3].predicates[0]=Path=/mail/**
spring.cloud.gateway.routes[3].filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

# CORS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
